INSERT INTO entreprise (nom_entreprise,mail,adresse,ville,site_web) 
VALUES 
('ENTREPRISE A', 'ENTREPRISE_A@gmail.com', 'A Rue du AAA', 'Ville A', 'AAA.com'),
('ENTREPRISE Z', 'ENTREPRISE_Z@gmail.com', 'Z Rue du ZZZ', 'Ville Z', 'ZZZ.com'),
('ENTREPRISE E', 'ENTREPRISE_E@gmail.com', 'E Rue du EEE', 'Ville E', 'EEE.com'),
('ENTREPRISE R', 'ENTREPRISE_R@gmail.com', 'R Rue du RRR', 'Ville R', 'RRR.com'),
('ENTREPRISE T', 'ENTREPRISE_T@gmail.com', 'T Rue du TTT', 'Ville T', 'TTT.com'),
('ENTREPRISE Y', 'ENTREPRISE_Y@gmail.com', 'Y Rue du YYY', 'Ville Y', 'YYY.com'),
('ENTREPRISE U', 'ENTREPRISE_U@gmail.com', 'U Rue du UUU', 'Ville U', 'UUU.com'),
('ENTREPRISE I', 'ENTREPRISE_I@gmail.com', 'I Rue du III', 'Ville I', 'III.com'),
('ENTREPRISE O', 'ENTREPRISE_O@gmail.com', 'O Rue du OOO', 'Ville O', 'OOO.com'),
('ENTREPRISE P', 'ENTREPRISE_P@gmail.com', 'P Rue du PPP', 'Ville P', 'PPP.com'),
('ENTREPRISE Q', 'ENTREPRISE_Q@gmail.com', 'Q Rue du QQQ', 'Ville Q', 'QQQ.com'),
('ENTREPRISE S', 'ENTREPRISE_S@gmail.com', 'S Rue du SSS', 'Ville S', 'SSS.com'),
('ENTREPRISE D', 'ENTREPRISE_D@gmail.com', 'D Rue du DDD', 'Ville D', 'DDD.com'),
('ENTREPRISE F', 'ENTREPRISE_F@gmail.com', 'F Rue du FFF', 'Ville F', 'FFF.com'),
('ENTREPRISE G', 'ENTREPRISE_G@gmail.com', 'G Rue du GGG', 'Ville G', 'GGG.com'),
('ENTREPRISE H', 'ENTREPRISE_H@gmail.com', 'H Rue du HHH', 'Ville H', 'HHH.com'),
('ENTREPRISE J', 'ENTREPRISE_J@gmail.com', 'J Rue du JJJ', 'Ville J', 'JJJ.com'),
('ENTREPRISE K', 'ENTREPRISE_K@gmail.com', 'K Rue du KKK', 'Ville K', 'KKK.com'),
('ENTREPRISE L', 'ENTREPRISE_L@gmail.com', 'L Rue du LLL', 'Ville L', 'LLL.com'),
('ENTREPRISE M', 'ENTREPRISE_M@gmail.com', 'M Rue du MMM', 'Ville M', 'MMM.com'),
('ENTREPRISE W', 'ENTREPRISE_W@gmail.com', 'W Rue du WWW', 'Ville W', 'WWW.com'),
('ENTREPRISE X', 'ENTREPRISE_X@gmail.com', 'X Rue du XXX', 'Ville X', 'XXX.com'),
('ENTREPRISE C', 'ENTREPRISE_C@gmail.com', 'C Rue du CCC', 'Ville C', 'CCC.com'),
('ENTREPRISE V', 'ENTREPRISE_V@gmail.com', 'V Rue du VVV', 'Ville V', 'VVV.com'),
('ENTREPRISE B', 'ENTREPRISE_B@gmail.com', 'B Rue du BBB', 'Ville B', 'BBB.com'),
('ENTREPRISE N', 'ENTREPRISE_N@gmail.com', 'N Rue du NNN', 'Ville N', 'NNN.com');