INSERT INTO etudiant (id_etude_id,nom_eleve,prenom_etudiant) 
VALUES 
('1', 'AAAAA', 'aaaaa'),
('1', 'ZZZZZ', 'zzzzz'),
('1', 'EEEEE', 'eeeee'),
('1', 'RRRRR', 'rrrrr'),
('1', 'TTTTT', 'ttttt'),
('1', 'YYYYY', 'yyyyy'),
('1', 'UUUUU', 'uuuuu'),
('1', 'IIIII', 'iiiii'),
('1', 'OOOOO', 'ooooo'),
('1', 'PPPPP', 'ppppp'),
('1', 'QQQQQ', 'qqqqq'),
('2', 'SSSSS', 'sssss'),
('2', 'DDDDD', 'ddddd'),
('2', 'FFFFF', 'fffff'),
('2', 'GGGGG', 'ggggg'),
('2', 'HHHHH', 'hhhhh'),
('2', 'JJJJJ', 'jjjjj'),
('2', 'KKKKK', 'kkkkk'),
('2', 'LLLLL', 'lllll'),
('2', 'MMMMM', 'mmmmm'),
('2', 'WWWWW', 'wwwww'),
('2', 'XXXXX', 'xxxxx'),
('2', 'CCCCC', 'ccccc'),
('2', 'VVVVV', 'vvvvv'),
('2', 'BBBBB', 'bbbbb'),
('2', 'NNNNN', 'nnnnn');